// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SlickGridPoC.Models;

public partial class Genre
{
    public int GenreId { get; set; }

    public string Name { get; set; }

    public virtual ICollection<MovieGenres> MovieGenres { get; } = new List<MovieGenres>();
}