// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using SlickGridPoC.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace SlickGridPoC.Models
{
    public partial interface ISlickDBContextProcedures
    {
        Task<List<GetMoviesResult>> GetMoviesAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
