// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SlickGridPoC.Models;

public partial class Movie
{
    public int MovieId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Storyline { get; set; }

    public int? Year { get; set; }

    public DateTime? ReleaseDate { get; set; }

    public int? Runtime { get; set; }

    public int Kind { get; set; }

    public virtual ICollection<MovieGenres> MovieGenres { get; } = new List<MovieGenres>();
}