// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using SlickGridPoC.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace SlickGridPoC.Models
{
    public partial class SlickDBContext
    {
        private ISlickDBContextProcedures _procedures;

        public virtual ISlickDBContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new SlickDBContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public ISlickDBContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<GetMoviesResult>().HasNoKey().ToView(null);
        }
    }

    public partial class SlickDBContextProcedures : ISlickDBContextProcedures
    {
        private readonly SlickDBContext _context;

        public SlickDBContextProcedures(SlickDBContext context)
        {
            _context = context;
        }

        public virtual async Task<List<GetMoviesResult>> GetMoviesAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<GetMoviesResult>("EXEC @returnValue = [dbo].[GetMovies]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
